name: 'Corellium'
description: 'Upload and execute code on a Corellium instance'
inputs:
  endpoint:
    description: 'deployment to use'
    required: true
  username:
    description: 'username to use'
    required: true
  password:
    description: 'password to use'
    required: true
  project:
    description: 'project to operate within'
    required: true
  instance:
    description: 'name of instance to use'
    required: true
  snapshot:
    description: 'name of snapshot to restore'
    required: false
    default: ''
  upload:
    description: 'asset to upload and expose as $ASSET_PATH'
    required: true
  run:
    description: 'shell command(s) to run'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
