name: 'Corellium'
description: 'Test code on a Corellium device'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  gateway:
    description: 'Gateway to connect to'
    required: true
  device:
    description: 'Name of device to use'
    required: true
  upload:
    description: 'Asset to upload and expose as $ASSET_PATH'
    required: true
  run:
    description: 'Shell command(s) to run'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
